import nmapDoc from '../../../docs/nmap.md?raw';

export const NMAP_DOC = nmapDoc;

export const SCAN_TYPES = [
  { value: 'syn', label: 'SYN Scan', flag: '-sS', note: 'QUÉT TCP ẩn (stealth): Gửi gói SYN, không hoàn thành TCP handshake → không bị ghi log. Quét nhanh, khó phát hiện. Cần quyền root. Phát hiện cổng TCP mở/đóng.' },
  { value: 'tcp', label: 'TCP Connect', flag: '-sT', note: 'QUÉT TCP đầy đủ: Hoàn thành TCP handshake (SYN→SYN-ACK→ACK). Dễ bị phát hiện, ghi log đầy đủ. Không cần root. Phát hiện cổng TCP mở/đóng. Dùng khi không có root.' },
  { value: 'udp', label: 'UDP Scan', flag: '-sU', note: 'QUÉT UDP: Gửi gói UDP đến cổng đích. Chậm hơn TCP do UDP không có handshake. Phát hiện dịch vụ UDP (DNS, SNMP, DHCP). Cổng mở thường không phản hồi, cổng đóng trả về ICMP port unreachable.' },
  { value: 'ping', label: 'Ping Sweep', flag: '-sn', note: 'QUÉT HOST: Chỉ phát hiện host đang hoạt động trong mạng, KHÔNG quét cổng. Gửi ICMP echo, TCP SYN/ACK, UDP. Nhanh, xác định IP nào đang online. Dùng để lập bản đồ mạng trước khi quét chi tiết.' },
];

export const TIMING_LABELS = [
  'T0 Paranoid',
  'T1 Sneaky',
  'T2 Polite',
  'T3 Normal',
  'T4 Aggressive',
  'T5 Insane',
];

export const COMMON_FLAGS = [
  {
    label: '--script vuln',
    value: '--script vuln',
    desc: 'Chạy các script phát hiện lỗ hổng bảo mật',
  },
  { label: '--script default', value: '--script default', desc: 'Chạy script NSE mặc định' },
  { label: '-sC', value: '-sC', desc: 'Tương đương --script default' },
  { label: '-sU', value: '-sU', desc: 'Quét UDP' },
  { label: '-sS', value: '-sS', desc: 'Quét SYN stealth (cần root)' },
  { label: '-sT', value: '-sT', desc: 'Quét TCP connect (không cần root)' },
  { label: '-sA', value: '-sA', desc: 'Quét ACK (phát hiện tường lửa)' },
  { label: '-sW', value: '-sW', desc: 'Quét Window' },
  { label: '-sM', value: '-sM', desc: 'Quét Maimon' },
  { label: '-sN', value: '-sN', desc: 'Quét TCP null' },
  { label: '-sF', value: '-sF', desc: 'Quét FIN' },
  { label: '-sX', value: '-sX', desc: 'Quét Xmas' },
  { label: '--scanflags', value: '--scanflags', desc: 'Tùy chỉnh cờ TCP' },
  { label: '-sI <zombie>', value: '-sI', desc: 'Quét idle (zombie)' },
  { label: '-sO', value: '-sO', desc: 'Quét giao thức IP' },
  { label: '-b <FTP relay>', value: '-b', desc: 'Quét FTP bounce' },
  { label: '-Pn', value: '-Pn', desc: 'Bỏ qua phát hiện host (không ping)' },
  { label: '-PS', value: '-PS', desc: 'Ping TCP SYN' },
  { label: '-PA', value: '-PA', desc: 'Ping TCP ACK' },
  { label: '-PU', value: '-PU', desc: 'Ping UDP' },
  { label: '-PY', value: '-PY', desc: 'Ping SCTP' },
  { label: '-PE', value: '-PE', desc: 'Ping ICMP echo' },
  { label: '-PP', value: '-PP', desc: 'Ping ICMP timestamp' },
  { label: '-PM', value: '-PM', desc: 'Ping ICMP netmask' },
  { label: '-PO', value: '-PO', desc: 'Ping giao thức IP' },
  { label: '-n', value: '-n', desc: 'Không phân giải DNS' },
  { label: '-R', value: '-R', desc: 'Luôn phân giải DNS' },
  { label: '--dns-servers', value: '--dns-servers', desc: 'Chỉ định máy chủ DNS' },
  { label: '--system-dns', value: '--system-dns', desc: 'Dùng DNS hệ thống' },
  { label: '-6', value: '-6', desc: 'Bật quét IPv6' },
  { label: '-A', value: '-A', desc: 'Quét aggressive (OS + version + scripts + traceroute)' },
  { label: '-O', value: '-O', desc: 'Phát hiện hệ điều hành' },
  { label: '--osscan-guess', value: '--osscan-guess', desc: 'Đoán OS mạnh hơn' },
  { label: '-sV', value: '-sV', desc: 'Phát hiện phiên bản dịch vụ' },
  { label: '--version-intensity', value: '--version-intensity', desc: 'Cường độ dò version (0-9)' },
  { label: '--version-light', value: '--version-light', desc: 'Dò version nhẹ (intensity 2)' },
  { label: '--version-all', value: '--version-all', desc: 'Thử tất cả probe version' },
  { label: '--script', value: '--script', desc: 'Chạy script NSE cụ thể' },
  { label: '--script-args', value: '--script-args', desc: 'Tham số cho script' },
  { label: '--script-trace', value: '--script-trace', desc: 'Hiển thị thực thi script' },
  { label: '--script-updatedb', value: '--script-updatedb', desc: 'Cập nhật cơ sở dữ liệu script' },
  { label: '-T0', value: '-T0', desc: 'Chậm nhất (paranoid)' },
  { label: '-T1', value: '-T1', desc: 'Rất chậm (sneaky)' },
  { label: '-T2', value: '-T2', desc: 'Chậm (polite)' },
  { label: '-T3', value: '-T3', desc: 'Bình thường' },
  { label: '-T4', value: '-T4', desc: 'Nhanh (aggressive)' },
  { label: '-T5', value: '-T5', desc: 'Rất nhanh (insane)' },
  { label: '--min-hostgroup', value: '--min-hostgroup', desc: 'Nhóm host song song tối thiểu' },
  { label: '--max-hostgroup', value: '--max-hostgroup', desc: 'Nhóm host song song tối đa' },
  { label: '--min-parallelism', value: '--min-parallelism', desc: 'Probe song song tối thiểu' },
  { label: '--max-parallelism', value: '--max-parallelism', desc: 'Probe song song tối đa' },
  { label: '--min-rtt-timeout', value: '--min-rtt-timeout', desc: 'Timeout RTT tối thiểu' },
  { label: '--max-rtt-timeout', value: '--max-rtt-timeout', desc: 'Timeout RTT tối đa' },
  { label: '--initial-rtt-timeout', value: '--initial-rtt-timeout', desc: 'Timeout RTT ban đầu' },
  { label: '--max-retries', value: '--max-retries', desc: 'Số lần thử lại tối đa' },
  { label: '--host-timeout', value: '--host-timeout', desc: 'Timeout cho mỗi host' },
  { label: '--scan-delay', value: '--scan-delay', desc: 'Độ trễ giữa các probe' },
  { label: '--max-scan-delay', value: '--max-scan-delay', desc: 'Độ trễ tối đa' },
  { label: '-f', value: '-f', desc: 'Phân mảnh gói tin' },
  { label: '-ff', value: '-ff', desc: 'Phân mảnh thành 8 byte' },
  { label: '--mtu', value: '--mtu', desc: 'Đặt MTU cho phân mảnh' },
  { label: '-D', value: '-D', desc: 'Quét với địa chỉ mồi (decoy)' },
  { label: '-S', value: '-S', desc: 'Giả mạo IP nguồn' },
  { label: '-e', value: '-e', desc: 'Chỉ định giao diện mạng' },
  { label: '-g', value: '-g', desc: 'Chỉ định cổng nguồn' },
  { label: '--source-port', value: '--source-port', desc: 'Chỉ định cổng nguồn' },
  { label: '--data-length', value: '--data-length', desc: 'Thêm dữ liệu ngẫu nhiên' },
  { label: '--ip-options', value: '--ip-options', desc: 'Tùy chọn IP' },
  { label: '--ttl', value: '--ttl', desc: 'Đặt TTL cho IP' },
  { label: '--spoof-mac', value: '--spoof-mac', desc: 'Giả mạo địa chỉ MAC' },
  { label: '--badsum', value: '--badsum', desc: 'Gửi checksum sai' },
  { label: '-oN', value: '-oN', desc: 'Xuất output dạng normal' },
  { label: '-oX', value: '-oX', desc: 'Xuất output dạng XML' },
  { label: '-oG', value: '-oG', desc: 'Xuất output dạng grepable' },
  { label: '-oA', value: '-oA', desc: 'Xuất tất cả định dạng' },
  { label: '-v', value: '-v', desc: 'Chi tiết (verbose)' },
  { label: '-vv', value: '-vv', desc: 'Rất chi tiết' },
  { label: '-d', value: '-d', desc: 'Gỡ lỗi (debug)' },
  { label: '--reason', value: '--reason', desc: 'Hiển thị lý do trạng thái cổng' },
  { label: '--open', value: '--open', desc: 'Chỉ hiển thị cổng mở' },
  { label: '--packet-trace', value: '--packet-trace', desc: 'Theo dõi gói tin' },
  { label: '--iflist', value: '--iflist', desc: 'Liệt kê giao diện mạng' },
  { label: '--append-output', value: '--append-output', desc: 'Ghi thêm vào file output' },
  { label: '--resume', value: '--resume', desc: 'Tiếp tục quét bị gián đoạn' },
  { label: '--stylesheet', value: '--stylesheet', desc: 'Stylesheet cho XML' },
  { label: '--webxml', value: '--webxml', desc: 'Dùng web XML stylesheet' },
  { label: '--no-stylesheet', value: '--no-stylesheet', desc: 'Bỏ qua stylesheet XML' },
];
