/**
 * Domain-specific Smart Category Groups for dynamic tab generation.
 */
import type { SmartCategoryGroup } from '../../../Person/types/smart-category';
import type { DomainDataCategory } from './domain-data-point';

export interface DomainCategoryGroup extends Omit<SmartCategoryGroup, 'categories'> {
  categories: DomainDataCategory[];
}

export const DOMAIN_CATEGORY_GROUPS: Omit<DomainCategoryGroup, 'isActive' | 'count'>[] = [
  {
    id: 'overview',
    label: 'Overview',
    icon: 'LayoutDashboard',
    accent: '#0af',
    categories: [],
    priority: 0,
    description: 'Tổng quan domain: DNS, subdomain, infrastructure, rủi ro',
  },
  {
    id: 'whois',
    label: 'WHOIS',
    icon: 'Fingerprint',
    accent: '#af52de',
    categories: [
      'whois_domain_name',
      'whois_registrar',
      'whois_registry',
      'whois_creation_date',
      'whois_expiration_date',
      'whois_updated_date',
      'whois_status',
      'whois_nameserver',
      'whois_registrant',
      'whois_admin_contact',
      'whois_tech_contact',
      'whois_raw',
      'whois_historical',
    ],
    priority: 1,
    description: 'Thông tin đăng ký domain, WHOIS hiện tại và lịch sử',
  },
  {
    id: 'dns',
    label: 'DNS Records',
    icon: 'Globe',
    accent: '#30d158',
    categories: [
      'dns_a_record',
      'dns_aaaa_record',
      'dns_mx_record',
      'dns_ns_record',
      'dns_soa_record',
      'dns_txt_record',
      'dns_cname_record',
      'dns_srv_record',
      'dns_ptr_record',
      'dns_caa_record',
      'dns_ds_record',
      'dns_dnskey_record',
      'dns_historical',
    ],
    priority: 2,
    description: 'Tất cả DNS records, so sánh giữa các DNS provider',
  },
  {
    id: 'subdomains',
    label: 'Subdomains',
    icon: 'Map',
    accent: '#0a84ff',
    categories: [
      'subdomain',
      'subdomain_takeover',
      'subdomain_wildcard',
      'subdomain_internal',
      'subdomain_cname',
    ],
    priority: 3,
    description: 'Subdomain được phát hiện từ crt.sh, AlienVault, SecurityTrails, DNSDB...',
  },
  {
    id: 'certificates',
    label: 'SSL/TLS Certs',
    icon: 'ShieldCheck',
    accent: '#64d2ff',
    categories: [
      'certificate',
      'cert_issuer',
      'cert_domains',
      'cert_validity',
      'cert_transparency_log',
    ],
    priority: 4,
    description: 'Chứng chỉ SSL/TLS từ Certificate Transparency logs',
  },
  {
    id: 'infrastructure',
    label: 'Infrastructure',
    icon: 'Network',
    accent: '#ff6b35',
    categories: [
      'asn',
      'cidr_range',
      'reverse_ip',
      'hosting_provider',
      'cloud_provider',
      'geo_location',
      'bgp_prefix',
      'peer_networks',
      'ip_address',
      'ipv6',
    ],
    priority: 5,
    description: 'Hạ tầng mạng: IP, ASN, hosting, CDN, geolocation',
  },
  {
    id: 'sensitive',
    label: 'Sensitive Exposure',
    icon: 'AlertTriangle',
    accent: '#ff375f',
    categories: [
      'env_exposure',
      'git_exposure',
      'backup_file',
      'config_file',
      'exposed_api_key',
      'exposed_secret_token',
      'firebase_config',
      'public_s3_bucket',
      'database_dump',
      'log_file',
      'source_code_exposure',
      'debug_endpoint',
      'admin_panel',
      'phpinfo_exposure',
    ],
    priority: 6,
    description: 'Lộ thông tin nhạy cảm: .env, .git, backup, API keys...',
  },
  {
    id: 'technology',
    label: 'Tech Stack',
    icon: 'Cpu',
    accent: '#64d2ff',
    categories: [
      'tech_framework',
      'tech_cms',
      'tech_server',
      'tech_cdn',
      'tech_analytics',
      'tech_javascript',
      'tech_ssl',
      'tech_header',
      'tech_cookie',
      'technology',
    ],
    priority: 7,
    description: 'Công nghệ phát hiện: framework, CMS, server, CDN, analytics',
  },
  {
    id: 'osint',
    label: 'OSINT',
    icon: 'Search',
    accent: '#ff9f0a',
    categories: [
      'google_dork',
      'wayback_snapshot',
      'social_mention',
      'news_mention',
      'forum_mention',
      'public_document',
      'file_metadata',
      'mobile_app',
    ],
    priority: 8,
    description: 'Google dorks, Wayback Machine, tài liệu công khai',
  },
  {
    id: 'emails',
    label: 'Emails',
    icon: 'Mail',
    accent: '#30d158',
    categories: ['harvested_email', 'email_pattern', 'catch_all_email', 'email'],
    priority: 9,
    description: 'Email thu thập được liên quan đến domain',
  },
  {
    id: 'people',
    label: 'People',
    icon: 'Users',
    accent: '#0a84ff',
    categories: ['employee_name', 'employee_email', 'employee_position'],
    priority: 10,
    description: 'Nhân sự liên quan: từ LinkedIn, GitHub, WHOIS...',
  },
  {
    id: 'mentions',
    label: 'Mentions',
    icon: 'MessageCircle',
    accent: '#f5a623',
    categories: ['social_mention', 'news_mention', 'forum_mention', 'internet_mention'],
    priority: 11,
    description: 'Đề cập trên mạng xã hội, diễn đàn, tin tức',
  },
  {
    id: 'network',
    label: 'Network',
    icon: 'Router',
    accent: '#ff6b35',
    categories: [
      'open_port',
      'service_banner',
      'http_response',
      'ssl_certificate_chain',
      'cors_header',
      'security_header',
      'port',
      'service',
    ],
    priority: 12,
    description: 'Port mở, service banners, HTTP response headers',
  },
  {
    id: 'related',
    label: 'Related Domains',
    icon: 'GitBranch',
    accent: '#af52de',
    categories: ['related_domain', 'sibling_domain', 'parked_domain'],
    priority: 13,
    description: 'Domain liên quan: cùng chủ sở hữu, cùng IP, parked domains',
  },
  {
    id: 'timeline',
    label: 'Timeline',
    icon: 'Clock',
    accent: '#5e5ce6',
    categories: [],
    priority: 14,
    description: 'Dòng thời gian thay đổi DNS, WHOIS, certificate',
  },
  {
    id: 'raw',
    label: 'Raw / Noise',
    icon: 'FileJson',
    accent: '#6a7a9a',
    categories: ['other', 'unclassified'],
    priority: 15,
    description: 'Dữ liệu thô chưa phân loại, false positives',
  },
  {
    id: 'sources',
    label: 'Sources',
    icon: 'Database',
    accent: '#6a7a9a',
    categories: [],
    priority: 16,
    description: 'Danh sách nguồn dữ liệu và độ tin cậy',
  },
];
