FROM golang:1.21-alpine AS builder

RUN apk add --no-cache git

RUN go install github.com/tomnomnom/assetfinder@latest

FROM alpine:latest

RUN apk add --no-cache ca-certificates

COPY --from=builder /go/bin/assetfinder /usr/local/bin/assetfinder

ENTRYPOINT ["assetfinder"]